import enum


class JobSourceEnum(str, enum.Enum):
    USER = "USER"
    AUTOMATED = "AUTOMATED"


class JobStatusEnum(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class KGVisibilityEnum(str, enum.Enum):
    ANONYMOUS = "anonymous"
    PUBLIC = "public"


class CheckStatusEnum(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class CheckOutcomeStatus(str, enum.Enum):
    OK = "ok"
    CONCERN = "concern"
    WARNING = "warning"
    PENDING = "pending"
    UNKNOWN = "unknown"


class CheckFindingCode(str, enum.Enum):
    TRIAL_ID_FOUND = "TRIAL_ID_FOUND"
    TRIAL_ID_NOT_FOUND = "TRIAL_ID_NOT_FOUND"
    TRIAL_ID_CHECK_FAILED = "TRIAL_ID_CHECK_FAILED"

    REGISTRY_CONFIRMED = "REGISTRY_CONFIRMED"
    REGISTRY_NOT_FOUND = "REGISTRY_NOT_FOUND"
    REGISTRY_LOOKUP_FAILED = "REGISTRY_LOOKUP_FAILED"

    TIMELINE_EXTRACTED = "TIMELINE_EXTRACTED"
    TIMELINE_NOT_AVAILABLE = "TIMELINE_NOT_AVAILABLE"
    TIMELINE_EXTRACTION_FAILED = "TIMELINE_EXTRACTION_FAILED"

    PROSPECTIVE_CONFIRMED = "PROSPECTIVE_CONFIRMED"
    RETROSPECTIVE_IDENTIFIED = "RETROSPECTIVE_IDENTIFIED"
    PROSPECTIVE_INDETERMINATE = "PROSPECTIVE_INDETERMINATE"
    PROSPECTIVE_ANALYSIS_FAILED = "PROSPECTIVE_ANALYSIS_FAILED"

    DOI_IDENTIFIED = "DOI_IDENTIFIED"
    DOI_NOT_FOUND = "DOI_NOT_FOUND"
    DOI_EXTRACTION_FAILED = "DOI_EXTRACTION_FAILED"

    REFERENCE_METADATA_CAPTURED = "REFERENCE_METADATA_CAPTURED"
    REFERENCE_METADATA_PARTIAL = "REFERENCE_METADATA_PARTIAL"
    REFERENCE_METADATA_FAILED = "REFERENCE_METADATA_FAILED"

    RETRACTION_MAIN_MATCH = "RETRACTION_MAIN_MATCH"
    RETRACTION_REFERENCE_MATCH = "RETRACTION_REFERENCE_MATCH"
    RETRACTION_NO_MATCH = "RETRACTION_NO_MATCH"
    RETRACTION_LOOKUP_FAILED = "RETRACTION_LOOKUP_FAILED"
    RETRACTION_CHECK_FAILED = "RETRACTION_CHECK_FAILED"

    EOC_CORRECTION_FOUND = "EOC_CORRECTION_FOUND"
    EOC_CORRECTION_CLEAR = "EOC_CORRECTION_CLEAR"
    EOC_CORRECTION_LOOKUP_FAILED = "EOC_CORRECTION_LOOKUP_FAILED"

    AUTHOR_HISTORY_FOUND = "AUTHOR_HISTORY_FOUND"
    AUTHOR_HISTORY_CLEAR = "AUTHOR_HISTORY_CLEAR"
    AUTHOR_HISTORY_LOOKUP_FAILED = "AUTHOR_HISTORY_LOOKUP_FAILED"

    PUBPEER_COMMENTS_FOUND = "PUBPEER_COMMENTS_FOUND"
    PUBPEER_NONE = "PUBPEER_NONE"
    PUBPEER_LOOKUP_FAILED = "PUBPEER_LOOKUP_FAILED"
    PUBPEER_NOT_FOUND = "PUBPEER_NOT_FOUND"


class SectionFindingCode(str, enum.Enum):
    REGISTRATION_PROSPECTIVE = "REGISTRATION_PROSPECTIVE"
    REGISTRATION_RETROSPECTIVE = "REGISTRATION_RETROSPECTIVE"
    REGISTRATION_INDETERMINATE = "REGISTRATION_INDETERMINATE"
    REGISTRATION_FAILED = "REGISTRATION_FAILED"

    RETRACTION_MATCH = "RETRACTION_MATCH"
    RETRACTION_CLEAR = "RETRACTION_CLEAR"
    RETRACTION_FAILED = "RETRACTION_FAILED"

    PUBPEER_COMMENTS = "PUBPEER_COMMENTS"
    PUBPEER_CLEAR = "PUBPEER_CLEAR"
    PUBPEER_FAILED = "PUBPEER_FAILED"
