"""Add composite indexes and schema fixes

Revision ID: 418fe11b4307
Revises: 53bd03ba16c6
Create Date: 2025-07-08 15:34:56.387561

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "418fe11b4307"
down_revision: Union[str, None] = "53bd03ba16c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_check_results_job_status",
        "check_results",
        ["job_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_check_results_job_status", table_name="check_results")
    # ### end Alembic commands ###
