"""add retraction watch tables

Revision ID: 6fb69923e6a6
Revises: e8f3d6a2b1c4
Create Date: 2025-10-21 17:01:06.135452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb69923e6a6'
down_revision: Union[str, None] = 'e8f3d6a2b1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('retractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('original_paper_doi', sa.String(length=255), nullable=True),
    sa.Column('original_paper_pubmed_id', sa.String(length=50), nullable=True),
    sa.Column('retraction_doi', sa.String(length=255), nullable=True),
    sa.Column('retraction_pubmed_id', sa.String(length=50), nullable=True),
    sa.Column('retraction_nature', sa.String(length=50), nullable=False),
    sa.Column('retraction_date', sa.Date(), nullable=True),
    sa.Column('original_paper_date', sa.Date(), nullable=True),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('article_type', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.Column('paywalled', sa.String(length=20), nullable=True),
    sa.Column('authors_fulltext', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retractions_date', 'retractions', [sa.literal_column('retraction_date DESC')], unique=False)
    op.create_index('idx_retractions_nature_date', 'retractions', ['retraction_nature', sa.literal_column('retraction_date DESC')], unique=False)
    op.create_index('idx_retractions_original_doi', 'retractions', ['original_paper_doi'], unique=False, postgresql_where=sa.text("original_paper_doi IS NOT NULL AND (original_paper_doi NOT IN ('Unavailable', 'unavailable', '0'))"))
    op.create_index('idx_retractions_title_gin', 'retractions', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_retractions_record_id'), 'retractions', ['record_id'], unique=True)
    op.create_index(op.f('ix_retractions_retraction_nature'), 'retractions', ['retraction_nature'], unique=False)
    op.create_table('retraction_authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retraction_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=500), nullable=False),
    sa.Column('author_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['retraction_id'], ['retractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_authors_name_lower', 'retraction_authors', ['author_name'], unique=False, postgresql_ops={'author_name': 'text_pattern_ops'})
    op.create_index('idx_unique_retraction_author', 'retraction_authors', ['retraction_id', 'author_name'], unique=True)
    op.create_index(op.f('ix_retraction_authors_retraction_id'), 'retraction_authors', ['retraction_id'], unique=False)
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_updated_at'), table_name='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_updated_at'), 'jobs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_jobs_status_created_at'), 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_retraction_authors_retraction_id'), table_name='retraction_authors')
    op.drop_index('idx_unique_retraction_author', table_name='retraction_authors')
    op.drop_index('idx_authors_name_lower', table_name='retraction_authors', postgresql_ops={'author_name': 'text_pattern_ops'})
    op.drop_table('retraction_authors')
    op.drop_index(op.f('ix_retractions_retraction_nature'), table_name='retractions')
    op.drop_index(op.f('ix_retractions_record_id'), table_name='retractions')
    op.drop_index('idx_retractions_title_gin', table_name='retractions', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_retractions_original_doi', table_name='retractions', postgresql_where=sa.text("original_paper_doi IS NOT NULL AND (original_paper_doi NOT IN ('Unavailable', 'unavailable', '0'))"))
    op.drop_index('idx_retractions_nature_date', table_name='retractions')
    op.drop_index('idx_retractions_date', table_name='retractions')
    op.drop_table('retractions')
    # ### end Alembic commands ###
